apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - monitoring.yaml
  - network-policies.yaml
  - pod-disruption-budgets.yaml
  - resource-quotas.yaml
  - drift-retrain-trigger.yaml
  - governance/model-registry-policies.yaml
  - dashboards/mlops-overview-dashboard.yaml
  - dashboards/cloud-cost-dashboard.yaml
