apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlops

resources:
  - namespace.yaml
  - ../../components/mlflow/
  - ../../components/kserve/

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: mlops-platform
