apiVersion: v1
kind: Namespace
metadata:
  name: mlops
  labels:
    app.kubernetes.io/name: mlops-platform
    app.kubernetes.io/component: namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: mlflow
  labels:
    app.kubernetes.io/name: mlops-platform
    app.kubernetes.io/component: mlflow
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubeflow
  labels:
    app.kubernetes.io/name: mlops-platform
    app.kubernetes.io/component: kubeflow
---
apiVersion: v1
kind: Namespace
metadata:
  name: kserve
  labels:
    app.kubernetes.io/name: mlops-platform
    app.kubernetes.io/component: kserve
